# ==========================================
# 基础路径设置
# ==========================================
music_directory    "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

# ==========================================
# 播放控制 (古典乐优化)
# ==========================================
auto_update          "yes"       # 自动发现新加入的 FLAC
restore_paused       "yes"       # 启动时恢复上次播放状态
metadata_to_use      "artist,album,title,track,name,genre,date,composer,performer,disc"
replaygain "off"        # 完全关闭（发烧推荐）
# 针对超高采样率 FLAC 的缓冲区优化，防止爆音
max_output_buffer_size "16384"

# ==========================================
# 音频输出 1：PipeWire (Max 兼容模式)
# ==========================================
audio_output {
    type            "pipewire"
    name            "PipeWire High-Res Output"
    # 允许 MPD 开启 DSD 播放 (如果有 DSD 资源)
    dop             "yes"
}


# ==========================================
# 可视化频谱 (针对 ncmpcpp)
# ==========================================
audio_output {
    type            "fifo"
    name            "Visualizer"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}

# ==========================================
# 联网协议
# ==========================================
bind_to_address    "127.0.0.1"
port               "6600"
