#using the foot terminal emulator as the default terminal
set -g default-terminal "foot"
set -g allow-passthrough on
set -as terminal-features 'foot:sixel'
set-option -a terminal-features 'foot:RGB'
set -s extended-keys on
set -as terminal-features 'foot:extkeys'
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
# switch panes using Alt-arrow and without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch panes using Alt-vim mode without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
# don't rename windows automatically
set-option -g allow-rename off
# set the base index
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g history-limit 10000000

# set the vim mode keymap to yank 
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
set -g renumber-windows on

set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}" 

# Pick a softer palette.
set -g @catppuccin_flavor 'frappe'
set -g @catppuccin_window_text " #{window_name}"
set -g @catppuccin_window_current_text " #{window_name}"
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_window_flags "icon"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line more pleasant.
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

